# FILE: ui_config.yaml
# Configurations for display, localization, and plotting defaults

variables_metadata:
  TMP:
    # Localization / Display Names
    name_en: "Temperature"
    name_fr: "Température"
    
    # Unit Options
    available_units: ["C", "F", "K"] # Must match keys in units.yaml
    grib_unit: "K"
    default_unit: "C"
    
    # Colormap & Visualization
    default_colormap: "thermal_r" # References a known colormap name
    
    vmin: -30
    vmax: 40

  wind_gust:
    # Localization / Display Names
    name_en: "Surface Wind Gusts"
    name_fr: "Rafales de Vent en Surface"
    
    # Unit Options
    available_units: ["m/s", "km/h", "knots", "mph"]
    grib_unit: "m/s"
    default_unit: "km/h"
    
    # Colormap & Visualization
    default_colormap: "wind_speed_sequential"
    vmin: 0
    vmax: 150
    
  REFC:
    name_en: "Réflectivité Composite"
    name_fr: "Composite Reflectivity"
    
    # Unit Options
    available_units: ["dBZ"] # Must match keys in units.yaml
    grib_unit: "dBZ"
    default_unit: "dBZ"
    
    # Colormap & Visualization
    default_colormap: "thermal_r" # References a known colormap name
    
    vmin: -30
    vmax: 100
    
levels_metadata:
    lev_entire_atmosphere: 
        name_en: ""
        name_fr: ""
    lev_2_m_above_ground:
        name_en: "2m AGL"
        name_fr: "2m AGL"